import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 
        Eat The Blocks (Youtube)
        Hash Time Locked Contract

        1. Bob picks a secret
        2. Bob cryptograph the hash of the secret
        3. Bob deploy a HTLC contract in Blockchain A
          3.1 Token A locked: with Alice's address & the secret 
        4. Bob sends Token A to the previous deployed HTLC contract

        The HTLC contract is coded to release Token A to Alice
        but only if she knows the secret.

        1. Alice will deploy another HTLC contract in Blockchain B
        2. Alice cryptograph the hash of the secret
        3. Alice deploy a HTLC contract in Blockchain B
          3.1 Token B locked: with Bob's address & the secret 
        4. Alice sends Token B to the previous deployed HTLC contract

        The HTLC contract is coded to release Token B to Alice
        but only if she knows the secret.

        5. Bob will withdraw Token B & will save the secret in the Blockchain B
        wich will reveal it publicly.
        6. Alice will read the value of the secret in Blockchain B & use it to withdraw
        Token A from Blockhain A.

        Security Risks:
        1. When the secret is revealed by Bob at Blockchain A, it will be 
        secured to Alice due the address which was given as parameter.
        2. If Bob never withdraw Token B & never reveal his secret
        the Token A won't be locked forever. Function "refund" is 
        responsible to return tokens after a certain amount of time.
        3. What if Bob withdraw Token B just before the time to activate
        the function "refund"? Make time shorter for Bob than for Alice.
      */}
      <main className={styles.main}></main>
    </div>
  );
}
